name: Build and start services
runs:
  using: composite
  steps:
    - name: Build Docker images
      shell: bash
      run: |
        echo "Building Docker images..."
        docker compose build
        
        echo "Starting services..."
        docker compose up -d
        
        echo "Waiting for services to be ready..."
        timeout 60 bash -c 'until curl -f -s http://localhost:3000 > /dev/null; do sleep 2; done' || echo "Frontend service timeout"
        timeout 60 bash -c 'until curl -f -s http://localhost:4000/ping > /dev/null; do sleep 2; done' || echo "Game service timeout"
        timeout 60 bash -c 'until curl -f -s http://localhost:8080 > /dev/null; do sleep 2; done' || echo "Tournament service timeout"
        
        echo "=== Docker Compose Services ==="
        docker compose ps 