name: Check service logs
runs:
  using: composite
  steps:
    - name: Check service logs
      shell: bash
      run: |
        echo "=== Frontend Logs ==="
        docker compose logs frontend
        
        echo "=== Game Logs ==="
        docker compose logs game
        
        echo "=== Tournament Logs ==="
        docker compose logs tournament