services:
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - 8181:8080
    environment:
      - SWAGGER_JSON=/api/tournament/v1/swagger.yml
    configs:
      - source: openapi-yml
        target: /api/tournament/v1/swagger.yml

  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports:
      - 8182:8080
    environment:
      - SWAGGER_JSON=/api/tournament/v1/swagger.yml
    configs:
      - source: openapi-yml
        target: /api/tournament/v1/swagger.yml
  

  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.oas3.yml'
    init: true
    ports:
      - '8183:4010'
    configs:
      - source: openapi-yml
        target: /tmp/api.oas3.yml
  
configs:
  openapi-yml:
    file: ./swagger.yml

volumes:
  tournament_node_modules:
