name: Docker Compose CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and start services
      uses: ./.github/workflows/actions/build-services.yml
    
    - name: Run Jest tests
      uses: ./.github/workflows/actions/run-tests.yml
    
    - name: Test service connectivity
      uses: ./.github/workflows/actions/test-connectivity.yml
    
    - name: Check service logs
      uses: ./.github/workflows/actions/check-logs.yml
    
    - name: Cleanup
      if: always()
      uses: ./.github/workflows/actions/cleanup.yml
