name: Docker Compose CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and start services
      run: |
        echo "Building Docker images..."
        docker compose build
        
        echo "Starting services..."
        docker compose up -d
        
        echo "Waiting for services to be ready..."
        sleep 45
        
        echo "Checking service status..."
        docker compose ps
    
    - name: Test service connectivity
      run: |
        echo "Testing frontend service..."
        curl -f http://localhost:3000 || echo "Frontend service not ready"
        
        echo "Testing game service..."
        curl -f http://localhost:4000/ping || echo "Game service not ready"
        
        echo "Testing tournament service..."
        curl -f http://localhost:8080 || echo "Tournament service not ready"
    
    - name: Check service logs
      run: |
        echo "=== Frontend Logs ==="
        docker compose logs frontend
        
        echo "=== Game Logs ==="
        docker compose logs game
        
        echo "=== Tournament Logs ==="
        docker compose logs tournament
    
    - name: Cleanup
      if: always()
      run: |
        echo "Stopping services..."
        docker compose down -v
        
        echo "Cleaning up images..."
        docker image prune -f