name: Docker Compose CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  COMPOSE_BAKE: false

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Run CI tests
      run: |
        chmod +x ./ci.sh
        ./ci.sh
    
    - name: Show service status
      if: always()
      run: |
        echo "=== Final Service Status ==="
        docker compose ps
        echo "=== Service Logs ==="
        docker compose logs --tail=20
    
    - name: Cleanup
      if: always()
      run: |
        docker compose down -v
        docker image prune -f
